[package]
name = "databases"
version = "0.0.0"
publish = false

[dependencies]
rocket = "0.4"
rusqlite = "0.13"
serde_derive = "1.0"
serde = "1.0"

[dependencies.rocket_contrib]
version = "0.4"
features = ["json", "sqlite_pool"]
